Config = {
    Events = {
        ["Shots Fired"] = {
            Text = {
                "~r~Shots fired ~w~by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                ""
            },
            Colour = 1,
            Bliptime = 120,
            Outlaw = true,
            Outlawtime = 120,
            Chance = 50,
            Populated = true,
            Ownershipcheck = false,
            Waittime = 5
        },
        ["Civil Disturbance"] = {
            Text = {
                "~r~Civil Disturbance ~w~involving a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                ""
            },
            Colour = 17,
            Bliptime = 60,
            Outlaw = true,
            Outlawtime = 60,
            Chance = 20,
            Populated = true,
            Ownershipcheck = false,
            Waittime = 15
        },
        ["Grand Theft Auto"] = {
            Text = {
                "~r~Grand Theft Auto ~w~of a ~r~",
                "veh",
                "~w~ by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2"
            },
            Colour = 5,
            Bliptime = 60,
            Outlaw = true,
            Outlawtime = 120,
            Chance = 75,
            Populated = false,
            Ownershipcheck = true,
            Waittime = 5
        },
        ["Vehicle Theft"] = {
            Text = {
                "Attempted ~r~theft ~w~of a ~r~",
                "veh",
                "~w~ by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2"
            },
            Colour = 5,
            Bliptime = 60,
            Outlaw = true,
            Outlawtime = 60,
            Chance = 25,
            Populated = true,
            Ownershipcheck = true,
            Waittime = 5
        },
        ["Weaponized Vehicle"] = {
            Text = {
                "Reports of a ~r~weaponized vehicle ~w~, a ~r~",
                "veh",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                ""
            },
            Colour = 1,
            Bliptime = 60,
            Outlaw = false,
            Outlawtime = 60,
            Chance = 5,
            Populated = true,
            Ownershipcheck = false,
            Waittime = 30
        },
        ["Car Chopping"] = {
            Text = {
                "Suspected ~r~car chopping ~w~by a ~r~",
                "veh",
                "~w~ by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2"
            },
            Colour = 5,
            Bliptime = 60,
            Outlaw = true,
            Outlawtime = 60,
            Chance = 60,
            Populated = false,
            Ownershipcheck = true,
            Waittime = 5
        },
        ["Drug Deal"] = {
            Text = {
                "Suspected ~r~drug deal ~w~by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                ""
            },
            Colour = 7,
            Bliptime = 60,
            Outlaw = true,
            Outlawtime = 60,
            Chance = 40,
            Populated = true,
            Ownershipcheck = false,
            Waittime = 5
        },
        ["Bank Robbery"] = {
            Text = {
                "~r~Bank Robbery ~w~by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                ""
            },
            Colour = 8,
            Bliptime = 300,
            Outlaw = true,
            Outlawtime = 180,
            Chance = 100,
            Populated = false,
            Ownershipcheck = false,
            Waittime = 5
        },
        ["Shop Robbery"] = {
            Text = {
                "~r~Shop Robbery ~w~by a ~r~",
                "sex",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                ""
            },
            Colour = 8,
            Bliptime = 240,
            Outlaw = true,
            Outlawtime = 120,
            Chance = 90,
            Populated = false,
            Ownershipcheck = false,
            Waittime = 5
        },
        ["Explosion"] = {
            Text = {
                "~r~Explosion ~w~reported ~r~",
                "atbetween",
                "street1",
                "xand",
                "street2",
                "",
                "",
                ""
            },
            Colour = 1,
            Bliptime = 120,
            Outlaw = false,
            Outlawtime = 120,
            Chance = 90,
            Populated = true,
            Ownershipcheck = false,
            Waittime = 1
        }
    },
    Zones = {
        All = {
            ['AIRP'] = "Los Santos International Airport", 
            ['ALAMO'] = "Alamo Sea", 
            ['ALTA'] = "Alta", 
            ['ARMYB'] = "Fort Zancudo", 
            ['BANHAMC'] = "Banham Canyon Dr", 
            ['BANNING'] = "Banning", 
            ['BEACH'] = "Vespucci Beach", 
            ['BHAMCA'] = "Banham Canyon", 
            ['BRADP'] = "Braddock Pass", 
            ['BRADT'] = "Braddock Tunnel", 
            ['BURTON'] = "Burton", 
            ['CALAFB'] = "Calafia Bridge", 
            ['CANNY'] = "Raton Canyon", 
            ['CCREAK'] = "Cassidy Creek", 
            ['CHAMH'] = "Chamberlain Hills", 
            ['CHIL'] = "Vinewood Hills", 
            ['CHU'] = "Chumash", 
            ['CMSW'] = "Chiliad Mountain State Wilderness", 
            ['CYPRE'] = "Cypress Flats", 
            ['DAVIS'] = "Davis", 
            ['DELBE'] = "Del Perro Beach", 
            ['DELPE'] = "Del Perro", 
            ['DELSOL'] = "Puerto Del Sol", 
            ['DESRT'] = "Grand Senora Desert", 
            ['DOWNT'] = "Downtown", 
            ['DTVINE'] = "Downtown Vinewood", 
            ['EAST_V'] = "East Vinewood", 
            ['EBURO'] = "El Burro Heights", 
            ['ELGORL'] = "El Gordo Lighthouse", 
            ['ELYSIAN'] = "Elysian Island", 
            ['GALFISH'] = "Galilee", 
            ['GOLF'] = "GWC and Golfing Society", 
            ['GRAPES'] = "Grapeseed", 
            ['GREATC'] = "Great Chaparral", 
            ['HARMO'] = "Harmony", 
            ['HAWICK'] = "Hawick", 
            ['HORS'] = "Vinewood Racetrack", 
            ['HUMLAB'] = "Humane Labs and Research", 
            ['JAIL'] = "Bolingbroke Penitentiary", 
            ['KOREAT'] = "Little Seoul", 
            ['LACT'] = "Land Act Reservoir", 
            ['LAGO'] = "Lago Zancudo", 
            ['LDAM'] = "Land Act Dam", 
            ['LEGSQU'] = "Legion Square", 
            ['LMESA'] = "La Mesa", 
            ['LOSPUER'] = "La Puerta", 
            ['MIRR'] = "Mirror Park", 
            ['MORN'] = "Morningwood", 
            ['MOVIE'] = "Richards Majestic", 
            ['MTCHIL'] = "Mount Chiliad", 
            ['MTGORDO'] = "Mount Gordo", 
            ['MTJOSE'] = "Mount Josiah", 
            ['MURRI'] = "Murrieta Heights", 
            ['NCHU'] = "North Chumash", 
            ['NOOSE'] = "N.O.O.S.E", 
            ['OCEANA'] = "Pacific Ocean", 
            ['PALCOV'] = "Paleto Cove", 
            ['PALETO'] = "Paleto Bay", 
            ['PALFOR'] = "Paleto Forest", 
            ['PALHIGH'] = "Palomino Highlands", 
            ['PALMPOW'] = "Palmer-Taylor Power Station", 
            ['PBLUFF'] = "Pacific Bluffs", 
            ['PBOX'] = "Pillbox Hill", 
            ['PROCOB'] = "Procopio Beach", 
            ['RANCHO'] = "Rancho", 
            ['RGLEN'] = "Richman Glen", 
            ['RICHM'] = "Richman", 
            ['ROCKF'] = "Rockford Hills", 
            ['RTRAK'] = "Redwood Lights Track", 
            ['SANAND'] = "San Andreas", 
            ['SANCHIA'] = "San Chianski Mountain Range", 
            ['SANDY'] = "Sandy Shores", 
            ['SKID'] = "Mission Row", 
            ['SLAB'] = "Slab City", 
            ['STAD'] = "Maze Bank Arena", 
            ['STRAW'] = "Strawberry", 
            ['TATAMO'] = "Tataviam Mountains", 
            ['TERMINA'] = "Terminal", 
            ['TEXTI'] = "Textile City", 
            ['TONGVAH'] = "Tongva Hills", 
            ['TONGVAV'] = "Tongva Valley", 
            ['VCANA'] = "Vespucci Canals", 
            ['VESP'] = "Vespucci", 
            ['VINE'] = "Vinewood", 
            ['WINDF'] = "Ron Alternates Wind Farm", 
            ['WVINE'] = "West Vinewood", 
            ['ZANCUDO'] = "Zancudo River", 
            ['ZP_ORT'] = "Port of South Los Santos", 
            ['ZQ_UAR'] = "Davis Quartz" 
        },
        Populated = {
            ['AIRP'] = "Los Santos International Airport", 
            -- ['ALAMO'] = "Alamo Sea", 
            ['ALTA'] = "Alta", 
            ['ARMYB'] = "Fort Zancudo", 
            ['BANHAMC'] = "Banham Canyon Dr", 
            ['BANNING'] = "Banning", 
            ['BEACH'] = "Vespucci Beach", 
            -- ['BHAMCA'] = "Banham Canyon", 
            -- ['BRADP'] = "Braddock Pass", 
            -- ['BRADT'] = "Braddock Tunnel", 
            ['BURTON'] = "Burton", 
            -- ['CALAFB'] = "Calafia Bridge", 
            -- ['CANNY'] = "Raton Canyon", 
            -- ['CCREAK'] = "Cassidy Creek", 
            ['CHAMH'] = "Chamberlain Hills", 
            ['CHIL'] = "Vinewood Hills", 
            ['CHU'] = "Chumash", 
            -- ['CMSW'] = "Chiliad Mountain State Wilderness", 
            ['CYPRE'] = "Cypress Flats", 
            ['DAVIS'] = "Davis", 
            ['DELBE'] = "Del Perro Beach", 
            ['DELPE'] = "Del Perro", 
            ['DELSOL'] = "Puerto Del Sol", 
            -- ['DESRT'] = "Grand Senora Desert", 
            ['DOWNT'] = "Downtown", 
            ['DTVINE'] = "Downtown Vinewood", 
            ['EAST_V'] = "East Vinewood", 
            ['EBURO'] = "El Burro Heights", 
            -- ['ELGORL'] = "El Gordo Lighthouse", 
            ['ELYSIAN'] = "Elysian Island", 
            ['GALFISH'] = "Galilee", 
            ['GOLF'] = "GWC and Golfing Society", 
            ['GRAPES'] = "Grapeseed", 
            -- ['GREATC'] = "Great Chaparral", 
            ['HARMO'] = "Harmony", 
            ['HAWICK'] = "Hawick", 
            ['HORS'] = "Vinewood Racetrack", 
            ['HUMLAB'] = "Humane Labs and Research", 
            ['JAIL'] = "Bolingbroke Penitentiary", 
            ['KOREAT'] = "Little Seoul", 
            -- ['LACT'] = "Land Act Reservoir", 
            ['LAGO'] = "Lago Zancudo", 
            ['LDAM'] = "Land Act Dam", 
            ['LEGSQU'] = "Legion Square", 
            ['LMESA'] = "La Mesa", 
            ['LOSPUER'] = "La Puerta", 
            ['MIRR'] = "Mirror Park", 
            ['MORN'] = "Morningwood", 
            ['MOVIE'] = "Richards Majestic", 
            -- ['MTCHIL'] = "Mount Chiliad", 
            -- ['MTGORDO'] = "Mount Gordo", 
            -- ['MTJOSE'] = "Mount Josiah", 
            ['MURRI'] = "Murrieta Heights", 
            ['NCHU'] = "North Chumash", 
            ['NOOSE'] = "N.O.O.S.E", 
            -- ['OCEANA'] = "Pacific Ocean", 
            -- ['PALCOV'] = "Paleto Cove", 
            ['PALETO'] = "Paleto Bay", 
            ['PALFOR'] = "Paleto Forest", 
            -- ['PALHIGH'] = "Palomino Highlands", 
            ['PALMPOW'] = "Palmer-Taylor Power Station", 
            ['PBLUFF'] = "Pacific Bluffs", 
            ['PBOX'] = "Pillbox Hill", 
            -- ['PROCOB'] = "Procopio Beach", 
            ['RANCHO'] = "Rancho", 
            ['RGLEN'] = "Richman Glen", 
            ['RICHM'] = "Richman", 
            ['ROCKF'] = "Rockford Hills", 
            -- ['RTRAK'] = "Redwood Lights Track", 
            -- ['SANAND'] = "San Andreas", 
            -- ['SANCHIA'] = "San Chianski Mountain Range", 
            ['SANDY'] = "Sandy Shores", 
            ['SKID'] = "Mission Row", 
            ['SLAB'] = "Slab City", 
            ['STAD'] = "Maze Bank Arena", 
            ['STRAW'] = "Strawberry", 
            -- ['TATAMO'] = "Tataviam Mountains", 
            ['TERMINA'] = "Terminal", 
            ['TEXTI'] = "Textile City", 
            -- ['TONGVAH'] = "Tongva Hills", 
            -- ['TONGVAV'] = "Tongva Valley", 
            ['VCANA'] = "Vespucci Canals", 
            ['VESP'] = "Vespucci", 
            ['VINE'] = "Vinewood", 
            -- ['WINDF'] = "Ron Alternates Wind Farm", 
            ['WVINE'] = "West Vinewood", 
            -- ['ZANCUDO'] = "Zancudo River", 
            ['ZP_ORT'] = "Port of South Los Santos", 
            ['ZQ_UAR'] = "Davis Quartz" 
        },
        Jurisdiction  = {
            ["Los Santos International Airport"] = "police", 
            ["Alamo Sea"] = "sheriff", 
            ["Alta"] = "police", 
            ["Fort Zancudo"] = "sheriff", 
            ["Banham Canyon Dr"] = "sheriff", 
            ["Banning"] = "police", 
            ["Vespucci Beach"] = "police", 
            ["Banham Canyon"] = "sheriff", 
            ["Braddock Pass"] = "sheriff", 
            ["Braddock Tunnel"] = "sheriff", 
            ["Burton"] = "police", 
            ["Calafia Bridge"] = "sheriff", 
            ["Raton Canyon"] = "sheriff", 
            ["Cassidy Creek"] = "sheriff", 
            ["Chamberlain Hills"] = "police", 
            ["Vinewood Hills"] = "police", 
            ["Chumash"] = "sheriff", 
            ["Chiliad Mountain State Wilderness"] = "sheriff", 
            ["Cypress Flats"] = "police", 
            ["Davis"] = "police", 
            ["Del Perro Beach"] = "police", 
            ["Del Perro"] = "police", 
            ["Puerto Del Sol"] = "police", 
            ["Grand Senora Desert"] = "sheriff", 
            ["Downtown"] = "police", 
            ["Downtown Vinewood"] = "police", 
            ["East Vinewood"] = "police", 
            ["El Burro Heights"] = "police", 
            ["El Gordo Lighthouse"] = "sheriff", 
            ["Elysian Island"] = "police", 
            ["Galilee"] = "sheriff", 
            ["GWC and Golfing Society"] = "police", 
            ["Grapeseed"] = "sheriff", 
            ["Great Chaparral"] = "sheriff", 
            ["Harmony"] = "sheriff", 
            ["Hawick"] = "police", 
            ["Vinewood Racetrack"] = "police", 
            ["Humane Labs and Research"] = "sheriff", 
            ["Bolingbroke Penitentiary"] = "sheriff", 
            ["Little Seoul"] = "police", 
            ["Land Act Reservoir"] = "sheriff", 
            ["Lago Zancudo"] = "sheriff", 
            ["Land Act Dam"] = "sheriff", 
            ["Legion Square"] = "police", 
            ["La Mesa"] = "police", 
            ["La Puerta"] = "police", 
            ["Mirror Park"] = "police", 
            ["Morningwood"] = "police", 
            ["Richards Majestic"] = "police", 
            ["Mount Chiliad"] = "sheriff", 
            ["Mount Gordo"] = "sheriff", 
            ["Mount Josiah"] = "sheriff", 
            ["Murrieta Heights"] = "police", 
            ["North Chumash"] = "sheriff", 
            ["N.O.O.S.E"] = "sheriff", 
            ["Pacific Ocean"] = "sheriff", 
            ["Paleto Cove"] = "sheriff", 
            ["Paleto Bay"] = "sheriff", 
            ["Paleto Forest"] = "sheriff", 
            ["Palomino Highlands"] = "sheriff", 
            ["Palmer-Taylor Power Station"] = "sheriff", 
            ["Pacific Bluffs"] = "police", 
            ["Pillbox Hill"] = "police", 
            ["Procopio Beach"] = "", 
            ["Rancho"] = "police", 
            ["Richman Glen"] = "police", 
            ["Richman"] = "police", 
            ["Rockford Hills"] = "police", 
            ["Redwood Lights Track"] = "sheriff", 
            ["San Andreas"] = "sheriff", 
            ["San Chianski Mountain Range"] = "sheriff", 
            ["Sandy Shores"] = "sheriff", 
            ["Mission Row"] = "police", 
            ["Slab City"] = "sheriff", 
            ["Maze Bank Arena"] = "police", 
            ["Strawberry"] = "police", 
            ["Tataviam Mountains"] = "sheriff", 
            ["Terminal"] = "police", 
            ["Textile City"] = "police", 
            ["Tongva Hills"] = "sheriff", 
            ["Tongva Valley"] = "sheriff", 
            ["Vespucci Canals"] = "police", 
            ["Vespucci"] = "police", 
            ["Vinewood"] = "police", 
            ["Ron Alternates Wind Farm"] = "sheriff", 
            ["West Vinewood"] = "police", 
            ["Zancudo River"] = "sheriff", 
            ["Port of South Los Santos"] = "police", 
            ["Davis Quartz"] = "sheriff"
        }
    }
}

Config.stealOwnChance = 10 -- Chance to trigger an alert for trying to steal your own car, compounds with other probabilities